apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: all-in-one-server-green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: all-in-one-server-green
        tbn_cluster: all-in-one-server
        stage: prod
        version: green
    spec:
      containers:
      - image: turbinelabs/all-in-one-server:0.8.1
        imagePullPolicy: IfNotPresent
        name: all-in-one-server
        env:
        - name: TBN_COLOR
          value: 83D061
        - name: TBN_NAME
          value: green
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
