apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: all-in-one-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: all-in-one-server
        tbn_cluster: all-in-one-server
        stage: prod
        version: blue
    spec:
      containers:
      - image: turbinelabs/all-in-one-server:latest
        imagePullPolicy: IfNotPresent
        name: all-in-one-server
        env:
        - name: TBN_COLOR
          value: 1B9AE4
        - name: TBN_NAME
          value: blue
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
