apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: all-in-one-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: all-in-one-client
        tbn_cluster: all-in-one-client
    spec:
      containers:
      - image: turbinelabs/all-in-one-client:0.6.1
        imagePullPolicy: IfNotPresent
        name: all-in-one-client
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
