apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tbncollect
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: tbncollect
    spec:
      containers:
      - image: turbinelabs/tbncollect:0.12.2
        imagePullPolicy: Always
        name: tbncollect
        env:
        - name: TBNCOLLECT_CMD
          value: kubernetes
        - name: TBNCOLLECT_API_ZONE_NAME
          value: testbed
        - name: TBNCOLLECT_API_KEY
          valueFrom:
            secretKeyRef:
              name: tbnsecret
              key: apikey
