apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tbnproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: tbnproxy
    spec:
      containers:
      - image: turbinelabs/tbnproxy:0.10.0
        imagePullPolicy: Always
        name: tbnproxy
        env:
        - name: TBNPROXY_PROXY_NAME
          value: testbed-proxy
        - name: TBNPROXY_API_ZONE_NAME
          value: testbed
        - name: TBNPROXY_API_KEY
          valueFrom:
            secretKeyRef:
              name: tbnsecret
              key: apikey
        ports:
        - containerPort: 80
          protocol: TCP
